import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { InputData, JSONSchemaInput, JSONSchemaStore, quicktype } from 'quicktype-core';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const SCHEMAS_DIR = path.join(rootDir, 'shared/schemas');
const TS_OUT_PATH = path.join(rootDir, 'shared/types/generated/wire-models.ts');
const KT_OUT_PATH = path.join(
  rootDir,
  'android/shared-models/src/main/java/com/poolpoker/shared/generated/WireModels.kt'
);
const BIOME_BIN = path.join(rootDir, 'node_modules/@biomejs/biome/bin/biome');

const isCheckMode = process.argv.includes('--check');

async function loadSchemas() {
  const schemaInput = new JSONSchemaInput(new JSONSchemaStore());
  const files = fs
    .readdirSync(SCHEMAS_DIR)
    .filter((f) => f.endsWith('.schema.json'))
    .sort();

  for (const file of files) {
    const fullPath = path.join(SCHEMAS_DIR, file);
    const content = JSON.parse(fs.readFileSync(fullPath, 'utf8'));
    if (content.definitions) {
      for (const [name, def] of Object.entries(content.definitions)) {
        await schemaInput.addSource({
          name,
          schema: JSON.stringify({
            $schema: 'http://json-schema.org/draft-07/schema#',
            title: name,
            ...def,
          }),
        });
      }
    }
  }

  return schemaInput;
}

function postProcessTypeScript(code) {
  let ts = code.replace(/\s*\[property: string\]: unknown;/g, '');
  ts = ts.replace(/\n{3,}/g, '\n\n');
  return `// Generated by scripts/codegen-models.mjs. DO NOT EDIT DIRECTLY.\n\n${ts.trim()}\n`;
}

function postProcessKotlin(code) {
  // Strip quicktype parse comment at the beginning
  let kt = code.replace(/^\/\/[^\n]*\n(?:\/\/([^\n]*\n|\n))*/m, '').trim();

  // Ensure uppercase snake_case for enum constants matching serial name
  kt = kt.replace(/@SerialName\("([^"]+)"\)\s+([A-Za-z0-9_]+)\(/g, (_match, serialName) => {
    const upperIdent = serialName.replace(/[-\s]/g, '_').toUpperCase();
    return `@SerialName("${serialName}") ${upperIdent}(`;
  });

  // Convert Long to Int except for timestamp fields
  kt = kt
    .split('\n')
    .map((line) => {
      if (line.includes('timestamp')) {
        return line;
      }
      return line.replace(/:\s*Long(\??)/g, ': Int$1').replace(/List<Long>/g, 'List<Int>');
    })
    .join('\n');

  // Add companion object to data classes so companion extension methods can be attached
  kt = kt.replace(/(data class [A-Za-z0-9_]+\s*\([\s\S]*?\n\))(?!\s*\{)/g, '$1 {\n    companion object\n}');

  // Clean up multiple blank lines
  kt = kt.replace(/\n{3,}/g, '\n\n');

  return `// Generated by scripts/codegen-models.mjs. DO NOT EDIT DIRECTLY.\n\n${kt.trim()}\n`;
}

function formatWithBiome(filePath) {
  if (fs.existsSync(BIOME_BIN)) {
    spawnSync(process.execPath, [BIOME_BIN, 'format', '--write', filePath], {
      stdio: 'ignore',
    });
  }
}

async function main() {
  console.log('📦 Reading schemas from shared/schemas/ ...');
  const schemaInput = await loadSchemas();
  const inputData = new InputData();
  inputData.addInput(schemaInput);

  console.log('⚡ Generating TypeScript wire models ...');
  const tsResult = await quicktype({
    inputData,
    lang: 'ts',
    rendererOptions: {
      'just-types': 'true',
      'acronym-style': 'original',
    },
  });
  const generatedTs = postProcessTypeScript(tsResult.lines.join('\n'));

  console.log('⚡ Generating Kotlin wire models (kotlinx.serialization) ...');
  const ktResult = await quicktype({
    inputData,
    lang: 'kotlin',
    rendererOptions: {
      framework: 'kotlinx',
      package: 'com.poolpoker.shared.generated',
      'acronym-style': 'original',
    },
  });
  const generatedKt = postProcessKotlin(ktResult.lines.join('\n'));

  // Ensure directories exist
  fs.mkdirSync(path.dirname(TS_OUT_PATH), { recursive: true });
  fs.mkdirSync(path.dirname(KT_OUT_PATH), { recursive: true });

  if (isCheckMode) {
    let hasDiff = false;
    // Format check TS by writing to a temporary file
    const tempTsPath = path.join(path.dirname(TS_OUT_PATH), '.wire-models.tmp.ts');
    fs.writeFileSync(tempTsPath, generatedTs, 'utf8');
    formatWithBiome(tempTsPath);
    const formattedTs = fs.readFileSync(tempTsPath, 'utf8');
    fs.unlinkSync(tempTsPath);

    if (!fs.existsSync(TS_OUT_PATH) || fs.readFileSync(TS_OUT_PATH, 'utf8') !== formattedTs) {
      console.error(`❌ TypeScript generated wire models are out of date: ${TS_OUT_PATH}`);
      hasDiff = true;
    }
    if (!fs.existsSync(KT_OUT_PATH) || fs.readFileSync(KT_OUT_PATH, 'utf8') !== generatedKt) {
      console.error(`❌ Kotlin generated wire models are out of date: ${KT_OUT_PATH}`);
      hasDiff = true;
    }

    if (hasDiff) {
      console.error('Please run "pnpm run codegen:models" to update generated wire models.');
      process.exit(1);
    } else {
      console.log('✅ Generated wire models are in sync with JSON schemas.');
      process.exit(0);
    }
  }

  fs.writeFileSync(TS_OUT_PATH, generatedTs, 'utf8');
  formatWithBiome(TS_OUT_PATH);
  console.log(`✅ Wrote TypeScript wire models to ${TS_OUT_PATH}`);

  fs.writeFileSync(KT_OUT_PATH, generatedKt, 'utf8');
  console.log(`✅ Wrote Kotlin wire models to ${KT_OUT_PATH}`);
}

main().catch((err) => {
  console.error('❌ Codegen failed:', err);
  process.exit(1);
});
